version: '2.1'
services:
  client:
    build: ./client
    container_name: client
    ports:
      - "8000:8000"
  server:
    build: ./server
    container_name: server
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
  mongo:
    image : mongo
    container_name: mongodb
    ports:
      - "27017:27017" 
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 3
      
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ubuntu/mongodb/database:/data/db
